### ISSUE TITLE
Undefined Offset Notice When Creating Table

### ISSUE THREAD

**Issue by cahilbey** [ThingEngineer/PHP-MySQLi-Database-Class#1027]
Hello,

I'm encountering an issue  while trying to create a temporary table:

```php
$SQL = "CREATE TEMPORARY TABLE TempOrder (
           OrderID INT AUTO_INCREMENT PRIMARY KEY,
           CustomerID INT
       ) ENGINE=InnoDB; ";
try{
    $RS = $db->rawQuery($SQL); 
}catch (\Exception $e) {
    echo $e->getMessage();
}
```

This SQL query successfully creates the temporary table. However, I am receiving a PHP notice:
```php
NOTICE: UNDEFINED OFFSET: 0 IN /... PHP/VENDOR/THINGENGINEER/MYSQLI-DATABASE-CLASS/MYSQLIDB.PHP ON LINE 559
```

Could you please provide some insight or guidance on what might be causing this notice and how to resolve it? Any help would be greatly appreciated.

Thank you

**Comment by huseyinaslim** [comment]
Your code for creating a temporary database table is running successfully. In PHP, try-catch blocks capture thrown errors. However, what you have mentioned here is not a thrown error, but a NOTICE type feedback. Therefore, it does not come from within the catch block and is completely unrelated to this code block.

This notice in PHP is received due to trying to call an invalid index of an array. For example;
```
<?php
$array = ['1' => 'apple', '2' => 'banana'];
echo $array[0];
```
Such a call would return the notice you received because there is no array element with index 0.

`NOTICE: UNDEFINED OFFSET: 0 IN /... PHP/VENDOR/THINGENGINEER/MYSQLI-DATABASE-CLASS/MYSQLIDB.PHP ON LINE 559
`
The reason you receive the notice seems to be due to a called array in the library returning empty, like not being able to find that index but to provide better assistance here, we need to know which version of the library you are using. However, this is feedback and not a critical error that will stop or disrupt the operation, so it can be ignored. Still, if you specify the version, we can understand what code the relevant line refers to and check the index in that area. Looking at the relevant line in the latest version, I don’t see a piece of code that could cause this error.

Have a good day.
