### ISSUE TITLE
How to check connection to db is success or not ?

### ISSUE THREAD

**Issue by amanjazari** [ThingEngineer/PHP-MySQLi-Database-Class#783]
Hi,
May i know how to check the status of db connection is successful or not ?
Thanks

**Comment by ricwein** [comment]
Hey @amanjazari, you can check the connection at runtime using the `ping()` method.

In addition, the `MysqliDb` class throws an exception it's unable to connect to the db in the first case.
But be aware, that the connection is established lazy only at execution of the first query, or interacting otherwise with the db-server. This includes running the `ping()` method itself.

```php
$db = new MysqliDb(...);

try {
  if (!$db->ping()) {
    echo 'not connected!';
    exit(1);
  }

  $db->get('users');
} catch (\Exception $e) {
  echo 'unable to connect: ' . $e->getMessage();
  exit(1);
}
```
