### ISSUE TITLE
IN / NOT IN with place holders not working or I'm doing it wrong?

### ISSUE THREAD

**Issue by neubreed** [ThingEngineer/PHP-MySQLi-Database-Class#814]
I'm having issues with placeholders for a where clause with IN and two strings:

`$db->where("(type NOT IN(?) OR type IS NULL)", ['discount','guest']);`

Which produces "Number of variables doesn't match number of parameters in prepared statement "

Tried putting the two values into a string: 

`$db->where("(type NOT IN(?) OR type IS NULL)", ['discount\', \'guest']);`

That didn't work so I ended up doing this:

`$typeNot = '"' . implode('","', $typeNot) . '"';
$sql = sprintf("(type NOT IN(%s) OR type IS NULL)", $typeNot);
$db->where($sql);`

Is there a better way to do an IN / NOT IN with IS NULL query with enclosed brackets () on the condition?

**Comment by abdalmonem** [comment]
try 
`$db->where("type NOT IN('" . explode(",", ['discount','guest']) . "') OR type IS NULL");`

**Comment by neubreed** [comment]
Thanks .. That produced `Warning: explode() expects parameter 2 to be string, array given` I swapped it with implode, added additional quotes and enclosing brackets and it worked .. thanks very much!

` $db->where("(type NOT IN('" . implode("','", ['discount','guest']) . "') OR type IS NULL)");`

**Comment by abdalmonem** [comment]
great ! , please do not forget t close the issue

**Comment by ricwein** [comment]
As long as your array is hard-coded and not received from user-input, the proposed answer is okay. But please don't use this, if your array is passed from a external input, since it would allow sql-injection attacks.

Instead I would propose the following answer(s):

> I'm not sure if the following works with a raw-where statement like this. Please test it ;) But it would be the most elegant solution.

If you really need to write the query as given (type is in array OR null):
```php
$validTypes = ['discount', 'guest'];

$db->where('(type NOT IN(?) OR type IS NULL)', [$validTypes]);
```
Pay attention to the 2-dimensional array for the second parameter: first dimension is an array which should be bound to the query (it could have more than one parameter (?-chars). The second dimension is the array which should be passed inside the IN(?) statement.

Else I would suggest something like this:

```php
$validTypes = ['discount', 'guest'];

$db->where('type', $validTypes, 'IN');
$db->orWhere('type IS NULL');
```

**Comment by neubreed** [comment]
Thanks for the help guys!

1a warned of and array to string conversion and failed

1b. worked. So I can see we need an ? for each  but it would be nice if multidimensional arrays as place holders where considered

The orWhere in no.2  didn't work in my case at I have another filter in the query .. 

`SELECT  * FROM ticket_type WHERE  type NOT IN ( 'discount', 'guest' )  OR type IS NULL AND event_id = '15'  ORDER BY weight ASC`

I need the IS NULL condition grouped with the IN in the above query

chrs.
